### ISSUE TITLE
Login/authentiaction hits problems

### ISSUE THREAD

**Issue by msw-mk2** [MartinHowarth/metaswitch-tinder#48]
400. That’s an error.

Error: redirect_uri_mismatch

The redirect URI in the request, http://metaswitch-tinder.herokuapp.com/oauth2_callback, does not match the ones authorized for the OAuth client. To update the authorized redirect URIs, visit: https://console.developers.google.com/apis/credentials/oauthclient/228552424448-cq22tllg54gfa966eacro1p7sj8jk96i.apps.googleusercontent.com?project=228552424448

Learn more

Request Details
response_type=code
client_id=228552424448-cq22tllg54gfa966eacro1p7sj8jk96i.apps.googleusercontent.com
redirect_uri=http://metaswitch-tinder.herokuapp.com/oauth2_callback
scope=email
That’s all we know.

**Comment by MartinHowarth** [comment]
Fixed. was http vs https problem.
